import React, { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Button } from "../ui/button";
import { Progress } from "../ui/progress";
import { ArrowRight, RefreshCw } from 'lucide-react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';

const quizData = [
  {
    question: '¿Qué quieres crear o mejorar principalmente?',
    options: [
      { text: 'Escribir o resumir textos', result: 'ChatGPT' },
      { text: 'Crear imágenes artísticas', result: 'MidJourney' },
      { text: 'Generar o editar videos', result: 'Runway' },
      { text: 'Analizar datos complejos', result: 'Gemini' },
    ],
  },
  {
    question: '¿Cuál es tu nivel de experiencia con herramientas de IA?',
    options: [
      { text: 'Soy totalmente nuevo', result: 'ChatGPT' },
      { text: 'He probado algunas', result: 'Claude AI' },
      { text: 'Tengo bastante experiencia', result: 'MidJourney' },
      { text: 'Soy un experto', result: 'Gemini' },
    ],
  },
  {
    question: '¿Qué valoras más en una herramienta?',
    options: [
      { text: 'Facilidad de uso', result: 'ChatGPT' },
      { text: 'Calidad visual profesional', result: 'MidJourney' },
      { text: 'Seguridad y ética', result: 'Claude AI' },
      { text: 'Versatilidad y potencia', result: 'Gemini' },
    ],
  },
  {
    question: '¿Prefieres herramientas gratuitas o estás dispuesto a pagar?',
    options: [
      { text: 'Gratuitas o con plan gratuito', result: 'ChatGPT' },
      { text: 'No me importa pagar por calidad', result: 'MidJourney' },
      { text: 'Busco la mejor relación calidad-precio', result: 'Claude AI' },
      { text: 'Necesito funciones empresariales', result: 'Gemini' },
    ],
  },
];

const toolInfo = {
  ChatGPT: { description: 'Ideal para empezar. Es versátil, fácil de usar y excelente para tareas de texto como escribir, resumir y conversar.', image: 'AI assistant generating text', alt: 'Ilustración de ChatGPT' },
  MidJourney: { description: 'La mejor opción para artistas y creativos. Genera imágenes de una calidad visual espectacular y única.', image: 'Surreal landscape generated by AI', alt: 'Ilustración de MidJourney' },
  Runway: { description: 'Perfecta para creadores de contenido. Ofrece un conjunto de herramientas de IA para editar y generar video de forma mágica.', image: 'AI editing video timeline', alt: 'Ilustración de Runway' },
  "Claude AI": { description: 'Si buscas un asistente seguro y con un razonamiento sólido, Claude es una excelente alternativa, especialmente para tareas profesionales.', image: 'Friendly AI robot waving', alt: 'Ilustración de Claude AI' },
  Gemini: { description: 'La herramienta más potente y multimodal. Es perfecta para usuarios avanzados que necesitan analizar diferentes tipos de datos (texto, imagen, código).', image: 'Two interconnected AI nodes', alt: 'Ilustración de Gemini' },
};

const Quiz = () => {
  const [currentQuestion, setCurrentQuestion] = useState(0);
  const [answers, setAnswers] = useState([]);
  const [showResult, setShowResult] = useState(false);

  const handleAnswer = (result) => {
    setAnswers([...answers, result]);
    if (currentQuestion < quizData.length - 1) {
      setCurrentQuestion(currentQuestion + 1);
    } else {
      setShowResult(true);
    }
  };

  const getResult = () => {
    const counts = answers.reduce((acc, curr) => {
      acc[curr] = (acc[curr] || 0) + 1;
      return acc;
    }, {});
    return Object.keys(counts).reduce((a, b) => (counts[a] > counts[b] ? a : b));
  };

  const restartQuiz = () => {
    setCurrentQuestion(0);
    setAnswers([]);
    setShowResult(false);
  };

  const progress = ((currentQuestion) / quizData.length) * 100;
  const resultTool = showResult ? getResult() : null;
  const resultData = resultTool ? toolInfo[resultTool] : null;

  return (
    <section id="quiz" className="py-20 sm:py-28 px-4 bg-[#0a0a0a]">
      <div className="container mx-auto text-center">
        <h2 className="text-4xl md:text-5xl font-bold mb-4 text-white">
          ¿Qué Herramienta de IA <span className="highlight-purple">Necesitas</span>?
        </h2>
        <p className="text-e0e0e0 mb-12 max-w-2xl mx-auto">Responde unas preguntas y descubre tu herramienta ideal.</p>

        <div className="max-w-3xl mx-auto bg-transparent p-8 rounded-2xl border-2 border-primary/30" style={{ background: 'rgba(45, 27, 78, 0.2)', backdropFilter: 'blur(10px)'}}>
          <AnimatePresence mode="wait">
            {!showResult ? (
              <motion.div
                key={currentQuestion}
                initial={{ opacity: 0, x: 50 }}
                animate={{ opacity: 1, x: 0 }}
                exit={{ opacity: 0, x: -50 }}
                transition={{ duration: 0.4, ease: 'easeInOut' }}
              >
                <Progress value={progress} className="mb-8 h-2 bg-primary/20" />
                <h3 className="text-2xl lg:text-3xl font-semibold mb-8 text-white">{quizData[currentQuestion].question}</h3>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  {quizData[currentQuestion].options.map((option, index) => (
                    <button
                      key={index}
                      onClick={() => handleAnswer(option.result)}
                      className="quiz-option-button"
                    >
                      {option.text}
                    </button>
                  ))}
                </div>
              </motion.div>
            ) : (
              <motion.div
                key="result"
                initial={{ opacity: 0, scale: 0.9 }}
                animate={{ opacity: 1, scale: 1 }}
                transition={{ duration: 0.5, ease: 'easeOut' }}
              >
                <Card className="bg-transparent border-none text-center">
                  <CardHeader>
                    <p className="text-lg text-e0e0e0">Tu herramienta recomendada es:</p>
                    <CardTitle className="text-5xl font-bold my-2 highlight-purple">{resultTool}</CardTitle>
                  </CardHeader>
                  <CardContent>
                    <div className="max-w-md mx-auto aspect-video bg-black rounded-lg mb-6 overflow-hidden border border-primary/30">
                       <img class="w-full h-full object-cover" alt={resultData.alt} src="https://images.unsplash.com/photo-1595872018818-97555653a011" />
                    </div>
                    <p className="text-e0e0e0 max-w-lg mx-auto">{resultData.description}</p>
                    <div className="mt-8 flex flex-col sm:flex-row justify-center gap-4">
                      <Button size="lg" onClick={() => document.getElementById('tools').scrollIntoView({ behavior: 'smooth' })}>
                        Explorar Herramientas <ArrowRight className="ml-2 h-5 w-5" />
                      </Button>
                      <Button size="lg" variant="outline" onClick={restartQuiz}>
                        <RefreshCw className="mr-2 h-5 w-5" /> Reiniciar Quiz
                      </Button>
                    </div>
                  </CardContent>
                </Card>
              </motion.div>
            )}
          </AnimatePresence>
        </div>
      </div>
    </section>
  );
};

export default Quiz;